#ifndef CONFIG_H
#define CONFIG_H

#define EZWIN_VERSION_MAJOR 1
#define EZWIN_VERSION_MINOR 0
#define EZWIN_VERSION_PATCH 0

#define EZWIN_IS_BUILT_AS_SHARED_LIB 0
#define EZWIN_IS_BUILT_AS_STATIC_LIB 1

#define X11_SUPPORT 1
#define WAYLAND_SUPPORT 1

#endif // CONFIG_H
